### ISSUE TITLE
twoje argumenty to gówno

### ISSUE THREAD

**Issue by TheVisionRo-Dak** [pankoza-pl/dlaczego-flash-to-kasztan#1]
Jest stary - no jest, ale dalej community go wspiera
    Nie napiszesz w nim żadnego porządniejszego programu - napiszesz, wiele gier jest zrobionych we flashu
    Działa tylko na windowsie i Internet Explorerze - lol nie, skąd masz tą informacje?
    Nie Jest językiem programowania - no, bo nie jest, ale actionscript już jest :>
    Nie ma w sobie nic przydatnego - ma
    Nie uczy programowania - uczy
    Miał służyć tylko do animacji, a teraz autystyczne dzieci piszą w nim "gry" - NIE XDDDDDDD
    Ma zły syntax - pewno nawet nie wiesz co to syntax
    HTML5 jest lepszy i nowocześniejszy - nie dla każdego
    Nie ma funkcji - co do kurwy
    pzpl i Vizja robią w nim "wirusy" - nigdy nie robiliśmy w nim wirusów idioto

**Comment by ProgramistaZpolski** [comment]
> Działa tylko na windowsie i Internet Explorerze

![Screenshot from 2021-05-21 12-50-21](https://user-images.githubusercontent.com/37271169/119126277-1e564200-ba33-11eb-946c-a20deba50069.png)

**Comment by TheVisionRo-Dak** [comment]
btw. i tak wiemy że trollujesz

**Comment by pankoza-pl** [comment]
> > Działa tylko na windowsie i Internet Explorerze
> 
> ![Screenshot from 2021-05-21 12-50-21](https://user-images.githubusercontent.com/37271169/119126277-1e564200-ba33-11eb-946c-a20deba50069.png)

wine

**Comment by pankoza-pl** [comment]
i nie śmiecić mi maila
